[WIP] Mandd/cpm red
idaholab/LOGOS pull request #52
Opened 2024-10-15 17:29 UTC by mandd

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual.
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Regression tests have to complete successfully.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [ ] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

2024-11-27 21:10 UTC, wangcj05 requested changes
I have some minor comments for you to consider. @mandd

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +  def __init__(self, name, duration, res=None, childs=None):
Add docstrings for all arguments in `__init__` method

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      self.childs = childs
please document all `self.variable` in this method.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +  def printToJsn(self):
function name is ok, but I think `printToJson` is better.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ In, None
add docstring for `childs`

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, file in jason format
There is no return for this function. Please update the docstring here.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +    #else:
remove?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, duration, float, duration of the activity
use `returnResources` instead of `duration`

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, None
update docstring here

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      graph_str += str(activity) + '\n'
camelBack?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +        print("Activity " + str(act.returnName()) + " requires a resource that is not allowed: " + str(act.returnResources()))
I would suggest to change all `print` to use `logging` instead. We have it configured and used in our LOGOS repo.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ In, endActivity activity, activity at the end of the path
`symbolic` is not documented in the docstring.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, pathsList, list of path that are parallel to the critical path
format of the docstring is not right. Provide the type after the variable.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, list, list of activities that are immediate successors of "node"
you can use the function name as `Out` in the docstring, when you do not have a specific name for the output.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, list, list of activities that are immediate predecessors of "node"
See previous comment.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, int, number activities that are immediate predecessors of "node"
same here, update the docstring, do you have the specific type for `node` argument.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ Out, list, list of activities
Update docstring here.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      @ In, node, activity, activity to be removed
Update docstring here.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      b_set = set(map(tuple,subpaths))
camelBack here?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +    c_set = set(map(tuple,subpathsSet))
camelBack here?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      nameFile = 'schedule.json'
You may provide default directly in the function definition.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +          pass'''
remove?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +def expandSubpaths(subpaths, path):
docstring is missing here.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +def checkForEndNode(listActivities):
docstring is missing here.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +    @ In, CP, list, list of activities
Please provide more details about these two variables, from the docstring, there is no difference between these two variables.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +def splitListRecursiveList(test_list, result, temp_list, particular_list):
camelBack for function arguments?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +    @ Out, result, list, list of subpaths that are part "path" parallel to "CP"
It seems the return is empty or no return for this function, please check the function return.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +  """
please update the docstring.

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +  unsupported_nodes = {n for n, d in G.nodes(data="node_type") if d == "unsupported"}
camelBack here?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +      _node_colors = [c for _, c in H.nodes(data="node_color")]
camelBack?

2024-11-27 21:10 UTC, wangcj05 commented on src/CPM/PertMain2.py
> +  G_minus_H = nx.DiGraph()
camelBack here?

2024-11-27 21:10 UTC, wangcj05 commented on tests/unit_tests/CPM/CPM.py
> +from __future__ import division, print_function, unicode_literals, absolute_import
I guess this can be removed

2025-01-16 18:30 UTC, mandd commented on src/CPM/PertMain2.py
> +  def __init__(self, name, duration, res=None, childs=None):
fixed

2025-01-16 18:34 UTC, mandd commented on src/CPM/PertMain2.py
> +      self.childs = childs
fixed

2025-01-16 18:36 UTC, mandd commented on src/CPM/PertMain2.py
> +  def printToJsn(self):
fixed

2025-01-16 18:38 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ In, None
fixed

2025-01-16 18:39 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, file in jason format
fixed

2025-01-16 18:44 UTC, mandd commented on src/CPM/PertMain2.py
> +    #else:
removed

2025-01-16 18:45 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, duration, float, duration of the activity
Fixed

2025-01-16 18:46 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, None
fixed

2025-01-16 18:48 UTC, mandd commented on src/CPM/PertMain2.py
> +      graph_str += str(activity) + '\n'
Fixed

2025-01-16 23:39 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ In, endActivity activity, activity at the end of the path
done!

2025-01-16 23:42 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, pathsList, list of path that are parallel to the critical path
fixed

2025-01-16 23:49 UTC, mandd commented on src/CPM/PertMain2.py
> +      b_set = set(map(tuple,subpaths))
fixed

2025-01-16 23:50 UTC, mandd commented on src/CPM/PertMain2.py
> +    c_set = set(map(tuple,subpathsSet))
fixed

2025-01-16 23:50 UTC, mandd commented on src/CPM/PertMain2.py
> +      nameFile = 'schedule.json'
fixed

2025-01-16 23:51 UTC, mandd commented on src/CPM/PertMain2.py
> +          pass'''
fixed

2025-01-17 00:14 UTC, mandd commented on src/CPM/PertMain2.py
> +def expandSubpaths(subpaths, path):
fixed

2025-01-17 00:14 UTC, mandd commented on src/CPM/PertMain2.py
> +def checkForEndNode(listActivities):
fixed

2025-01-17 00:20 UTC, mandd commented on src/CPM/PertMain2.py
> +def splitListRecursiveList(test_list, result, temp_list, particular_list):
Fixed

2025-01-17 00:22 UTC, mandd commented on src/CPM/PertMain2.py
> +  unsupported_nodes = {n for n, d in G.nodes(data="node_type") if d == "unsupported"}
Fixed

2025-01-17 00:22 UTC, mandd commented on src/CPM/PertMain2.py
> +      _node_colors = [c for _, c in H.nodes(data="node_color")]
Fixed

2025-01-17 00:23 UTC, mandd commented on src/CPM/PertMain2.py
> +  G_minus_H = nx.DiGraph()
fixed

2025-01-17 00:23 UTC, mandd commented on tests/unit_tests/CPM/CPM.py
> +from __future__ import division, print_function, unicode_literals, absolute_import
removed

2025-01-20 21:23 UTC, mandd reviewed
@wangcj05: I think all comments have been addressed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +        print("Activity " + str(act.returnName()) + " requires a resource that is not allowed: " + str(act.returnResources()))
added but needs to be discussed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, list, list of activities that are immediate successors of "node"
fixed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, list, list of activities that are immediate predecessors of "node"
fixed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, int, number activities that are immediate predecessors of "node"
fixed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ Out, list, list of activities
fixed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +      @ In, node, activity, activity to be removed
fixed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +    @ In, CP, list, list of activities
edited

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +    @ Out, result, list, list of subpaths that are part "path" parallel to "CP"
Fixed

2025-01-20 21:23 UTC, mandd commented on src/CPM/PertMain2.py
> +  """
fixed

2025-01-27 16:48 UTC, wangcj05 approved these changes
changes are good.

2025-01-27 17:07 UTC, wangcj05 commented
changes are good, checklist is good.

2025-01-27 17:07 UTC, merged